/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely'

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>

export type Timestamp = ColumnType<
  Date,
  Date | string,
  Date | string
>

export interface Household {
  id: Generated<number>
  name: string
  profilePicture: string | null
}

export interface Ingredient {
  expiryDate: Timestamp
  householdId: number
  id: Generated<number>
  isReady: Generated<boolean>
  name: string
  nextNotif: Timestamp | null
  note: string | null
  notifInterval: number | null
  purchaseDate: Timestamp
  quantity: Generated<number>
  storage: string
  type: string
  unit: string
}

export interface Leftover {
  expiryDate: Generated<Timestamp>
  householdId: number
  id: Generated<number>
  mealId: number
  portions: number
}

export interface Meal {
  eatingDate: Timestamp
  householdId: number
  id: Generated<number>
  outsideMeal: string | null
  portions: number
  recipeId: number | null
}

export interface Member {
  householdId: number | null
  roleId: number | null
  userId: number
}

export interface Participant {
  attended: Generated<boolean>
  confirmation: boolean | null
  mealId: number
  userId: number
}

export interface RcpIngr {
  amount: number
  householdId: number
  ingredientId: number
  recipeId: number
  unit: string
}

export interface Recipe {
  description: string
  householdId: number
  id: Generated<number>
  img: string | null
  name: string
  portions: number
  prepTime: number
  public: Generated<boolean>
  tips: string | null
  vid: string | null
}

export interface Role {
  id: Generated<number>
  name: string
}

export interface User {
  allergies: string | null
  diet: string | null
  email: string
  id: Generated<number>
  name: string
  password: string
  profilePicture: string | null
}

export interface DB {
  household: Household
  ingredient: Ingredient
  leftover: Leftover
  meal: Meal
  member: Member
  participant: Participant
  rcpIngr: RcpIngr
  recipe: Recipe
  role: Role
  user: User
}
